rm(list = ls(all.names = TRUE)); gc()
ROOT <- normalizePath(getwd(), winslash = "/", mustWork = TRUE)
source(file.path(ROOT, "R", "project_loader.R"), local = FALSE)
source_project_files(ROOT); assert_project_api(); load_project_packages()
cfg <- read_project_config(file.path(ROOT, "config", "default.yml"), ROOT); configure_runtime(cfg)
scfg <- smooth_config(cfg, "primary")
dat <- prepare_mortality_data(scfg)
pack <- build_smooth_data(dat, scfg)
fit <- fit_smooth_cohort_model(pack, scfg)
saveRDS(pack, file.path(scfg$output_dir, "stan_pack.rds"))
summarise_smooth_diagnostics(fit, scfg, pack, "smooth")
